name: Cross-platform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on self-hosted Linux runner
    runs-on: [self-hosted, linux-build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build sample image
        run: |
          docker build -t myorg/sample-app:ci-${{ github.run_id }} ./exercises/02-containerize-app/app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-image-tag
          path: ./exercises/02-containerize-app/app

  build-windows:
    name: Build on self-hosted Windows runner
    runs-on: [self-hosted, windows-build]
    steps:
      - uses: actions/checkout@v4
      - name: Build artifact (example)
        run: echo "Windows build step placeholder"
      - name: Ensure artifact folder
        run: mkdir -p ./artifacts/windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: ./artifacts/windows

  publish:
    name: Publish
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Publish placeholder
        run: echo "Publish step (register in registry or release)"
